In [ ]:
data = pd.read_csv('/Users/danielmorantes/PythonP/Analítica_Comp_Uniandes/Proyecto1/Proyecto1_Analcomp/DataAWS.csv')
data["periodo"][0]
valor = data["periodo"][0]+data["periodo"][1]
valor

In [ ]:
#Initial view of the data
raw_data = pd.read_csv('/Users/danielmorantes/PythonP/Analítica_Comp_Uniandes/Proyecto1/Proyecto1_Analcomp/DataAWS.csv')
raw_data.head()

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20162,TI,SB11201620604627,URBANO,N,A,TÉCNICO/ACADÉMICO,115238000698,115238000698,15,...,NaN,NaN,NaN,A2,61.00,59.00,63.0,57.0,56.0,295.0
1,20132,TI,SB11201320007175,URBANO,N,A,TÉCNICO/ACADÉMICO,315762000076,315762000076,15,...,Si,Si,No,A1,43.00,52.00,NaN,NaN,NaN,NaN
2,20102,CC,SB11201020409042,URBANO,N,A,TÉCNICO,115790000031,115790000031,15,...,Si,Si,Si,A-,38.53,45.38,NaN,NaN,NaN,NaN
3,20142,TI,SB11201420116599,RURAL,N,A,TÉCNICO/ACADÉMICO,215759000524,215759000524,15,...,Si,No,No,A1,52.00,55.00,54.0,60.0,54.0,277.0
4,20152,TI,SB11201520349379,URBANO,N,A,TÉCNICO,115835000283,115835000283,15,...,No,No,Si,A1,55.00,52.00,50.0,53.0,47.0,254.0

In [ ]:
raw_data.shape

(215234, 51)

In [ ]:
#Colums names
raw_data.columns

Index(['periodo', 'estu_tipodocumento', 'estu_consecutivo',
       'cole_area_ubicacion', 'cole_bilingue', 'cole_calendario',
       'cole_caracter', 'cole_cod_dane_establecimiento', 'cole_cod_dane_sede',
       'cole_cod_depto_ubicacion', 'cole_cod_mcpio_ubicacion',
       'cole_codigo_icfes', 'cole_depto_ubicacion', 'cole_genero',
       'cole_jornada', 'cole_mcpio_ubicacion', 'cole_naturaleza',
       'cole_nombre_establecimiento', 'cole_nombre_sede',
       'cole_sede_principal', 'estu_cod_depto_presentacion',
       'estu_cod_mcpio_presentacion', 'estu_cod_reside_depto',
       'estu_cod_reside_mcpio', 'estu_depto_presentacion', 'estu_depto_reside',
       'estu_estadoinvestigacion', 'estu_estudiante', 'estu_fechanacimiento',
       'estu_genero', 'estu_mcpio_presentacion', 'estu_mcpio_reside',
       'estu_nacionalidad', 'estu_pais_reside', 'estu_privado_libertad',
       'fami_cuartoshogar', 'fami_educacionmadre', 'fami_educacionpadre',
       'fami_estratovivienda', 'fami_personashogar', 'fami_tieneautomovil',
       'fami_tienecomputador', 'fami_tieneinternet', 'fami_tienelavadora',
       'desemp_ingles', 'punt_ingles', 'punt_matematicas',
       'punt_sociales_ciudadanas', 'punt_c_naturales', 'punt_lectura_critica',
       'punt_global'],
      dtype='object')

In [ ]:
#Nan values
raw_data.isna().sum()

periodo                              0
estu_tipodocumento                   0
estu_consecutivo                     0
cole_area_ubicacion                 80
cole_bilingue                    17277
cole_calendario                     49
cole_caracter                      980
cole_cod_dane_establecimiento        0
cole_cod_dane_sede                   0
cole_cod_depto_ubicacion             0
cole_cod_mcpio_ubicacion             0
cole_codigo_icfes                 1616
cole_depto_ubicacion                 0
cole_genero                          0
cole_jornada                         0
cole_mcpio_ubicacion                 0
cole_naturaleza                      0
cole_nombre_establecimiento          0
cole_nombre_sede                     0
cole_sede_principal                  0
estu_cod_depto_presentacion          0
estu_cod_mcpio_presentacion          0
estu_cod_reside_depto             1234
estu_cod_reside_mcpio             1234
estu_depto_presentacion              0
estu_depto_reside                 1234
estu_estadoinvestigacion             0
estu_estudiante                      0
estu_fechanacimiento                 0
estu_genero                        121
estu_mcpio_presentacion              0
estu_mcpio_reside                 1234
estu_nacionalidad                    0
estu_pais_reside                     0
estu_privado_libertad                0
fami_cuartoshogar                 3530
fami_educacionmadre               7424
fami_educacionpadre               7459
fami_estratovivienda              5522
fami_personashogar                3573
fami_tieneautomovil               3561
fami_tienecomputador              5515
fami_tieneinternet                5067
fami_tienelavadora                3487
desemp_ingles                       33
punt_ingles                          3
punt_matematicas                     0
punt_sociales_ciudadanas         83150
punt_c_naturales                 83150
punt_lectura_critica             83150
punt_global                      83150
dtype: int64

In [ ]:
raw_data.isna().sum(axis=0)/raw_data.shape[0]*100

periodo                           0.000000
estu_tipodocumento                0.000000
estu_consecutivo                  0.000000
cole_area_ubicacion               0.037169
cole_bilingue                     8.027078
cole_calendario                   0.022766
cole_caracter                     0.455318
cole_cod_dane_establecimiento     0.000000
cole_cod_dane_sede                0.000000
cole_cod_depto_ubicacion          0.000000
cole_cod_mcpio_ubicacion          0.000000
cole_codigo_icfes                 0.750811
cole_depto_ubicacion              0.000000
cole_genero                       0.000000
cole_jornada                      0.000000
cole_mcpio_ubicacion              0.000000
cole_naturaleza                   0.000000
cole_nombre_establecimiento       0.000000
cole_nombre_sede                  0.000000
cole_sede_principal               0.000000
estu_cod_depto_presentacion       0.000000
estu_cod_mcpio_presentacion       0.000000
estu_cod_reside_depto             0.573329
estu_cod_reside_mcpio             0.573329
estu_depto_presentacion           0.000000
estu_depto_reside                 0.573329
estu_estadoinvestigacion          0.000000
estu_estudiante                   0.000000
estu_fechanacimiento              0.000000
estu_genero                       0.056218
estu_mcpio_presentacion           0.000000
estu_mcpio_reside                 0.573329
estu_nacionalidad                 0.000000
estu_pais_reside                  0.000000
estu_privado_libertad             0.000000
fami_cuartoshogar                 1.640075
fami_educacionmadre               3.449269
fami_educacionpadre               3.465531
fami_estratovivienda              2.565580
fami_personashogar                1.660054
fami_tieneautomovil               1.654478
fami_tienecomputador              2.562328
fami_tieneinternet                2.354182
fami_tienelavadora                1.620097
desemp_ingles                     0.015332
punt_ingles                       0.001394
punt_matematicas                  0.000000
punt_sociales_ciudadanas         38.632372
punt_c_naturales                 38.632372
punt_lectura_critica             38.632372
punt_global                      38.632372
dtype: float64

In [ ]:
raw_data["periodo"].unique()

array([20162, 20132, 20102, 20142, 20152, 20172, 20194, 20122, 20112,
       20141, 20224, 20111, 20201, 20101, 20151, 20121, 20131, 20181,
       20211, 20221])

In [ ]:
cols = ["punt_lectura_critica","punt_c_naturales","punt_sociales_ciudadanas","punt_ingles","punt_matematicas"]
raw_data.groupby("periodo")[cols].count()

,punt_lectura_critica,punt_c_naturales,punt_sociales_ciudadanas,punt_ingles,punt_matematicas
periodo,,,,,
20101,0,0,0,658,658
20102,0,0,0,20202,20202
20111,0,0,0,487,487
20112,0,0,0,20235,20235
20121,0,0,0,460,460
20122,0,0,0,22352,22352
20131,0,0,0,340,340
20132,0,0,0,18109,18109
20141,0,0,0,307,307
20142,17325,17325,17325,17325,17325
20151,299,299,299,299,299
20152,16538,16538,16538,16538,16538
20162,16840,16840,16840,16840,16840
20172,16872,16872,16872,16872,16872
20181,87,87,87,87,87
20194,33474,33474,33474,33474,33474
20201,94,94,94,94,94
20211,65,65,65,64,65
20221,120,120,120,120,120
20224,30370,30370,30370,30368,30370